---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

ci:
  autofix_commit_msg: "Chore: pre-commit autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: 5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      # - id: double-quote-string-fixer
      - id: detect-private-key
      - id: end-of-file-fixer
      # - id: file-contents-sorter
      # - id: fix-byte-order-marker
      # - id: forbid-new-submodules
      # - id: forbid-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=master
          - --branch=main
          - --branch=rc
          - --branch=production
      # - id: pretty-format-json
      - id: requirements-txt-fixer
      # id: sort-simple-yaml
      # files: ^config/simple/
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98 # frozen: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        stages: [pre-commit]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: be92e15345b32661abee2e675d765ae79686eb4c # frozen: v1.37.0
    hooks:
      - id: yamllint
        types: [yaml]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: a23f6b85d0fdd5bb9d564e2579e678033debbdff # frozen: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: a185be0fd5b45112845b700d91b81050c75579e2 # frozen: v1.7.7.23
    hooks:
      - id: actionlint

  - repo: https://github.com/openstack/bashate
    rev: 5798d24d571676fc407e81df574c1ef57b520f23 # frozen: 2.1.1
    hooks:
      - id: bashate
        args: ["--ignore=E006,E011"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0 # frozen: v0.42.0
    hooks:
      - id: markdownlint
        args: ["--fix"]

  - repo: https://github.com/fsfe/reuse-tool
    rev: 60dfc6b2ad9e1f3eabfbcf3a0dc202ee89dc5a00 # frozen: v5.0.2
    hooks:
      - id: reuse

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: e84319e627902e1b348574ecf3238dc511933dc7 # frozen: v0.11.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: 63c8f8312b7559622c0d82815639671ae42132ac # frozen: v2.4.1
    hooks:
      - id: codespell
